### PR TITLE
Replace generic array with vec

### LINKED ISSUE #31: Swap crate compiles very slowly
Adding message1 is when compile times become slow. This is the comit where it becomes slow. Swap compiles fast before this commit.
[0f17ec076c09f064e62dd6ccac6d1c08f57b71a7](https://github.com/comit-network/xmr-btc-swap/commit/0f17ec076c09f064e62dd6ccac6d1c08f57b71a7)

This is the preceding commit that compiles fast
[5395303a99b0e66a5380e8d14ba48f573d6950fc](https://github.com/comit-network/xmr-btc-swap/commit/5395303a99b0e66a5380e8d14ba48f573d6950fc)

First commit with swap crate that compiles (fast): 
[hu04e1dca16afdb0834c8758ce0bc8eed3796812ec ](https://github.com/comit-network/xmr-btc-swap/commit/hu04e1dca16afdb0834c8758ce0bc8eed3796812ec )

### PR DESCRIPTION
**Pull request by rishflab**
This speeds up the painfully slow compilation of the swap crate in
xmr-btc-swap.

Attempt to fix https://github.com/comit-network/xmr-btc-swap/issues/31

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
🎊

**Review by thomaseizinger — COMMENTED** [review]
I assume @luckysori wanted to get the typesystem to verify certain properties by using `GenericArray` instead of `Vec`? Have you thought about how this is affected once `GenericArray` is no longer used?

I assume the refactoring towards `Vec` will require quite a bit more changes then just replacing `GenericArray` with `Vec`, starting with `Vec` taking only a single type parameter :D

Edit: I see @luckysori is actually part of the commit, should be fine then :)

**Comment by luckysori** [comment]
> Edit: I see @luckysori is actually part of the commit, should be fine then :)

Hehe, I just rebased onto master now that I added CI and force pushed so that this cannot be merged by mistake.

But yeah, type safety was the main reason behind using `GenericArray`. We were trying to verify if giving up the type safety would resolve our slow compilation in `xmr-btc-swap`, but we have to make it compile first 😛. In any case, I recommend replacing this library with `secp256kfun/sigma_fun` as soon as https://github.com/LLFourn/secp256kfun/pull/29 is merged.

**Comment by bonomat** [comment]
> > Edit: I see @luckysori is actually part of the commit, should be fine then :)
> 
> Hehe, I just rebased onto master now that I added CI and force pushed so that this cannot be merged by mistake.
> 
> But yeah, type safety was the main reason behind using `GenericArray`. We were trying to verify if giving up the type safety would resolve our slow compilation in `xmr-btc-swap`, but we have to make it compile first 😛. In any case, I recommend replacing this library with `secp256kfun/sigma_fun` as soon as [LLFourn/secp256kfun#29](https://github.com/LLFourn/secp256kfun/pull/29) is merged.

This PR makes use of `GenericArrays` as well unfortunately. 

CC @LLFourn

**Pull request merged**
